spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_SERVER}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

    driverClassName: org.postgresql.Driver
    platform: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
      location:  ${FILE_PATH}

server:
  servlet:
    context-path: /file
  port: 6070

feign:
  hystrix:
    enabled: true

security:
  oauth2:
    client:
      client-id: file-service
      client-secret: ${FILE_SERVICE_PASSWORD}
      access-token-uri: http://auth-service:5001/uaa/oauth/token
      grant-type: client_credentials
      scope: server
