spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice_tmp
    username: postgres
    password: postgres
#    url: ${POSTGRES_DB}
#    username: ${POSTGRES_USER}
#    password: ${POSTGRES_PASSWORD}

    driverClassName: org.postgresql.Driver
    platform: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true

assm:
  app:
    jwtExpiration: 86400
    jwtSecret: jwtAssmKeySecret@34ADilet02MDsP
app:
  token:
    email:
      verification:
        duration: 3600000
    password:
      reset:
        duration: 3600000
    refresh:
      duration: 604800000

server:
  servlet:
    context-path: /uaa
  port: 5001
