#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 20000
#
#ribbon:
#  ReadTimeout: 20000
#  ConnectTimeout: 20000

#zuul:
#  ignoredServices: '*'
#  host:
#    connect-timeout-millis: 20000
#    socket-timeout-millis: 20000
#
#  routes:
#    auth-service:
#        path: /uaa/**
#        url: http://localhost:5001
#        stripPrefix: false
#        sensitiveHeaders:
#
#    user-service:
#        path: /user/**
#        serviceId: user-service
##        url: http://localhost:6008
#        stripPrefix: false
#        sensitiveHeaders:
#
#    statistics-service:
#        path: /statistics/**
#        serviceId: statistics-service
#        stripPrefix: false
#        sensitiveHeaders:
#
#    notification-service:
#        path: /notifications/**
#        serviceId: notification-service
#        stripPrefix: false
#        sensitiveHeaders:

spring:
  cloud:
    gateway:
      routes:
        - id: user_service
          uri: lb://USER-SERVICE/
          predicates:
            - Path=/users/**
        - id: auth_service
          uri: lb://AUTH-SERVICE/
          predicates:
            - Path=/uaa/**
      discovery:
        locator:
          enabled: true

server:
  port: 4000
